// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD32IFZRZpSi30w3Zlznlb3sWhtpxg5ilw',
    appId: '1:505924088824:web:5c1b9b19ff6ec28767dc0d',
    messagingSenderId: '505924088824',
    projectId: 'node-users-c60ae',
    authDomain: 'node-users-c60ae.firebaseapp.com',
    storageBucket: 'node-users-c60ae.firebasestorage.app',
    measurementId: 'G-TV8HCZ3TNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa8m-2QjEWP0f9zJdBty3z-UQqWDUaIXM',
    appId: '1:505924088824:android:90069fb7530e4ec967dc0d',
    messagingSenderId: '505924088824',
    projectId: 'node-users-c60ae',
    storageBucket: 'node-users-c60ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5-huua8_yuPKHJRhTdAAtwsVw55qjRLA',
    appId: '1:505924088824:ios:dabcc0f5c8e7166d67dc0d',
    messagingSenderId: '505924088824',
    projectId: 'node-users-c60ae',
    storageBucket: 'node-users-c60ae.firebasestorage.app',
    iosClientId: '505924088824-afi0pivcsogpaipmd0uvvirk43lbtcm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileFavor',
  );
}
