/**
 * @fileoverview gRPC-Web generated client stub for delivery
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.3
// source: delivery.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.delivery = require('./delivery_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.delivery.DeliveryServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.delivery.DeliveryServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.delivery.SearchDriversRequest,
 *   !proto.delivery.SearchDriversResponse>}
 */
const methodDescriptor_DeliveryService_SearchDrivers = new grpc.web.MethodDescriptor(
  '/delivery.DeliveryService/SearchDrivers',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.delivery.SearchDriversRequest,
  proto.delivery.SearchDriversResponse,
  /**
   * @param {!proto.delivery.SearchDriversRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.delivery.SearchDriversResponse.deserializeBinary
);


/**
 * @param {!proto.delivery.SearchDriversRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.delivery.SearchDriversResponse>}
 *     The XHR Node Readable Stream
 */
proto.delivery.DeliveryServiceClient.prototype.searchDrivers =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/delivery.DeliveryService/SearchDrivers',
      request,
      metadata || {},
      methodDescriptor_DeliveryService_SearchDrivers);
};


/**
 * @param {!proto.delivery.SearchDriversRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.delivery.SearchDriversResponse>}
 *     The XHR Node Readable Stream
 */
proto.delivery.DeliveryServicePromiseClient.prototype.searchDrivers =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/delivery.DeliveryService/SearchDrivers',
      request,
      metadata || {},
      methodDescriptor_DeliveryService_SearchDrivers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.delivery.DriverLocation,
 *   !proto.delivery.UpdateDriverLocation>}
 */
const methodDescriptor_DeliveryService_updateDriverLocation = new grpc.web.MethodDescriptor(
  '/delivery.DeliveryService/updateDriverLocation',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.delivery.DriverLocation,
  proto.delivery.UpdateDriverLocation,
  /**
   * @param {!proto.delivery.DriverLocation} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.delivery.UpdateDriverLocation.deserializeBinary
);


/**
 * @param {!proto.delivery.DriverLocation} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.delivery.UpdateDriverLocation>}
 *     The XHR Node Readable Stream
 */
proto.delivery.DeliveryServiceClient.prototype.updateDriverLocation =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/delivery.DeliveryService/updateDriverLocation',
      request,
      metadata || {},
      methodDescriptor_DeliveryService_updateDriverLocation);
};


/**
 * @param {!proto.delivery.DriverLocation} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.delivery.UpdateDriverLocation>}
 *     The XHR Node Readable Stream
 */
proto.delivery.DeliveryServicePromiseClient.prototype.updateDriverLocation =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/delivery.DeliveryService/updateDriverLocation',
      request,
      metadata || {},
      methodDescriptor_DeliveryService_updateDriverLocation);
};


module.exports = proto.delivery;

